### ISSUE TITLE
Error running test.py

### ISSUE THREAD

**Issue by rpalcab** [Shamir-Lab/PlasClass#7]
Hi,

I've followed the installation instructions and everything went fine, but when running test.py I'm getting a non-zero exit status 1. The complete output is:

```
Testing...
Traceback (most recent call last):
  File "test/test.py", line 62, in <module>
    all_tests()
  File "test/test.py", line 57, in all_tests
    test_fasta_classifier()
  File "test/test.py", line 10, in test_fasta_classifier
    subprocess.check_call(cmd, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/home/user/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python /home/user/PlasClass/classify_fasta.py -f /home/user/PlasClass/test/test.fa -o /home/user/PlasClass/test/test.out' returned non-zero exit status 1.
```
How can I fix this issue?

Thanks!

**Comment by dpellow** [comment]
Can you check what is the output when you just run the command that causes the error:
`python /home/user/PlasClass/classify_fasta.py -f /home/user/PlasClass/test/test.fa -o /home/user/PlasClass/test/test.out` ?

Are you running it inside a virtual environment?

**Comment by rpalcab** [comment]
Thanks for the quick answer! I'm running it inside a conda environment

This is the output of 
`python /home/user/PlasClass/classify_fasta.py -f /home/user/PlasClass/test/test.fa -o /home/user/PlasClass/test/test.out`:
```
Loading classifier 1000
/home/user/anaconda3/lib/python3.8/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.linear_model.logistic module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/user/anaconda3/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/home/user/anaconda3/lib/python3.8/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.preprocessing.data module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.preprocessing. Anything that cannot be imported from sklearn.preprocessing is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/user/anaconda3/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator StandardScaler from version 0.19.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
Loading classifier 10000
Loading classifier 100000
Loading classifier 500000
Reading test/test.fa in batches of 100k sequences
Read 62 sequences
62 sequences to classify. Classifying in batches of 100k
Starting new batch
Getting kmer frequencies for partition length 1000
Traceback (most recent call last):
  File "classify_fasta.py", line 73, in <module>
    main(args)
  File "classify_fasta.py", line 64, in main
    probs = c.classify(seqs)
  File "/home/user/PlasClass/plasclass/plasclass.py", line 62, in classify
    standardized_freqs = self._standardize(kmer_freqs_mat, scale)
  File "/home/user/PlasClass/plasclass/plasclass.py", line 105, in _standardize
    return self.classifiers[scale]['scaler'].transform(freqs)
  File "/home/user/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 791, in transform
    X = self._validate_data(X, reset=False,
  File "/home/user/anaconda3/lib/python3.8/site-packages/sklearn/base.py", line 436, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/home/user/anaconda3/lib/python3.8/site-packages/sklearn/base.py", line 372, in _check_n_features
    raise RuntimeError(
RuntimeError: The reset parameter is False but there is no n_features_in_ attribute. Is this estimator fitted?
```

**Comment by dpellow** [comment]
Thanks for the information. It seems like this is due to an incompatible version of scikit-learn. PlasClass pins scikit-learn version to 0.21.3 but it seems you have version 0.23.2 in you environment. (I'm not sure why the pin to the older version didn't work).

It looks like an update in version 0.22 and late is incompatible with the version PlasClass uses.
You should install the required version of scikit-learn and try again.
Let me know if that works.

(PS let me know if you can tell why the correct version wasn't used when installing PlasClass)

**Comment by rpalcab** [comment]
That's right! As you indicated, there was a problem of incompatibility between scikit-learn 0.23.2 and PlasClass.

Apparently, scikit-learn 0.21.3 is not supported by Python 3.8 (maybe that's the reason why it wasn't installed when running setup.py). I created a new environment with Python 3.6 and scikit-learn 0.21.3 and the test worked perfectly fine.

Thank you!
